In [1]:
import numpy as np

In [2]:
myList = [1,2,3,4,5]

In [3]:
np.array(myList)

array([1, 2, 3, 4, 5])

In [4]:
my2dlist = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my2dlist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(2,20,2) # start end step (end is not included)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.linspace(1,15,6)

array([ 1. ,  3.8,  6.6,  9.4, 12.2, 15. ])

In [12]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
arr2d = arr.reshape(4,4)
arr2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
arr2d[3][2]

14

In [16]:
arr2d[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [17]:
rno = [1,2,3,4,5,6,7,8,9,10]
np.array(rno)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
subarray = rno[0:3]

In [19]:
subarray

[1, 2, 3]

In [29]:
newarr = np.arange(3,10)
copyarr = newarr.copy()
sliced = newarr[0:4]
sliced

array([3, 4, 5, 6])

In [30]:
sliced[:] = 77

In [31]:
sliced

array([77, 77, 77, 77])

In [32]:
newarr

array([77, 77, 77, 77,  7,  8,  9])

In [33]:
copyarr

array([3, 4, 5, 6, 7, 8, 9])

In [34]:
copyarr[copyarr>7]

array([8, 9])

In [35]:
copyarr*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [36]:
copyarr+10

array([13, 14, 15, 16, 17, 18, 19])

In [37]:
np.sqrt(copyarr)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        ])

In [38]:
a = [1,2,3]
b = [4,5,6]
np.cross(a,b)

array([-3,  6, -3])

In [39]:
np.dot(a,b)

32

In [40]:
matrix = [[0,1], [2,3]]

In [41]:
np.transpose(matrix)

array([[0, 2],
       [1, 3]])

In [42]:
np.mean(matrix)

1.5

In [43]:
np.cov(matrix)

array([[0.5, 0.5],
       [0.5, 0.5]])